# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 01:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'permissions': [['view_apply', 'Can view apply']],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'permissions': [['view_bookmark', 'Can view bookmark']],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'permissions': [['view_comment', 'Can view comment']],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'Request'), ('D', 'Denied'), ('A', 'Approved')], default='R', max_length=1)),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('requested_date', models.DateField(default=django.utils.timezone.now)),
                ('joined_date', models.DateField(null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_team_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [['view_membership', 'Can view membership']],
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'permissions': [['view_share', 'Can view share']],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5120)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=1)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_count', models.IntegerField(default=0)),
                ('bookmark_count', models.IntegerField(default=0)),
                ('apply_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(to='classification.Category')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_team_leaders', to=settings.AUTH_USER_MODEL)),
                ('member', models.ManyToManyField(through='organization.Membership', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [['view_team', 'Can view team']],
            },
        ),
        migrations.AddField(
            model_name='share',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Team'),
        ),
        migrations.AddField(
            model_name='share',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Team'),
        ),
        migrations.AddField(
            model_name='comment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Team'),
        ),
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Team'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apply',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Team'),
        ),
        migrations.AddField(
            model_name='apply',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_applies', to=settings.AUTH_USER_MODEL),
        ),
    ]
