# Generated by Django 2.1.7 on 2019-02-21 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={},
        ),
    ]
