# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 01:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('S', 'Sent'), ('R', 'Received')], default='S', max_length=1)),
                ('box', models.CharField(choices=[('I', 'InBox'), ('A', 'ArchiveBox'), ('D', 'DeleteBox')], default='I', max_length=1)),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('receive_time', models.DateTimeField(blank=True, null=True)),
                ('archive_time', models.DateTimeField(blank=True, null=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messagebox.Message')),
            ],
            options={
                'permissions': [['view_message', 'Can view message']],
            },
        ),
    ]
